<script>
  import { api } from './api.js'
  import BuildLog from './BuildLog.svelte'

  let { info, refresh } = $props()

  let modalId = $state('')
  let modalSecret = $state('')
  let buildBusy = $state(false)
  let buildError = $state('')

  let showDirect = $state(false)
  let directUrl = $state('')
  let directBusy = $state(false)
  let directError = $state('')

  let copied = $state(false)

  async function deployModal(e) {
    e.preventDefault()
    buildBusy = true
    buildError = ''
    try {
      await api('POST', '/setup/build', { modal_token_id: modalId.trim(), modal_token_secret: modalSecret.trim() })
      modalSecret = ''
      await refresh()
    } catch (err) {
      buildError = err.message
    } finally {
      buildBusy = false
    }
  }

  async function saveDirect(e) {
    e.preventDefault()
    directBusy = true
    directError = ''
    try {
      await api('POST', '/setup/generator', { base_url: directUrl.trim() })
      await refresh()
    } catch (err) {
      directError = err.message
    } finally {
      directBusy = false
    }
  }

  async function copyConnector() {
    await navigator.clipboard.writeText(info.connector_url)
    copied = true
    setTimeout(() => (copied = false), 1500)
  }

  async function rotate() {
    if (!confirm('Make a new connector URL? The old one stops working, so you will need to update it in claude.ai.')) return
    await api('POST', '/setup/rotate-connector')
    await refresh()
  }
</script>

<p class="muted">
  Worker <code>{info.cloudflare.script}</code> in account <code>{info.cloudflare.account_id}</code>. Logging in
  again with a new token replaces the stored one.
</p>

<section>
  <h2>1. GPU</h2>
  {#if info.generator}
    <p class="ok">
      Ready: {info.generator.kind === 'modal' ? 'ComfyUI on Modal' : 'a ComfyUI at'} <code>{info.generator.base_url}</code>.
    </p>
  {/if}
  <p>
    Images are generated by ComfyUI on <a href="https://modal.com" target="_blank" rel="noopener">Modal</a>, which
    only runs (and bills) while generating. New accounts get $30 of free compute a month; a card must be on file.
  </p>
  <ol>
    <li>In Modal, open <b>Settings → API Tokens</b> and click <b>New Token</b>.</li>
    <li>Paste both parts here. They are stored only as build secrets, used to deploy ComfyUI into your Modal account.</li>
  </ol>
  <form onsubmit={deployModal}>
    <label for="mid">Token ID</label>
    <input id="mid" type="text" bind:value={modalId} placeholder="ak-…" autocomplete="off" />
    <label for="msec">Token secret</label>
    <input id="msec" type="password" bind:value={modalSecret} placeholder="as-…" autocomplete="off" />
    <button type="submit" disabled={buildBusy || !modalId.trim() || !modalSecret.trim()}>
      {buildBusy ? 'Starting…' : 'Deploy to Modal'}
    </button>
    {#if buildError}<p class="err">{buildError}</p>{/if}
  </form>
  {#if info.build}
    {#key info.build}<BuildLog onfinished={refresh} />{/key}
  {/if}

  <p>
    <button class="secondary" onclick={() => (showDirect = !showDirect)}>
      {showDirect ? 'Hide' : 'Advanced: use a ComfyUI URL instead'}
    </button>
  </p>
  {#if showDirect}
    <form onsubmit={saveDirect}>
      <label for="url">ComfyUI URL</label>
      <input id="url" type="url" bind:value={directUrl} placeholder="https://comfy.example.com" />
      <p class="muted">It must be reachable from the internet. The Worker checks <code>/system_stats</code> before saving.</p>
      <button type="submit" disabled={directBusy || !directUrl.trim()}>{directBusy ? 'Checking…' : 'Use this ComfyUI'}</button>
      {#if directError}<p class="err">{directError}</p>{/if}
    </form>
  {/if}
</section>

<section>
  <h2>2. Connect Claude</h2>
  <p>Add this URL in claude.ai: <b>Settings → Connectors → Add custom connector</b>.</p>
  <div class="row">
    <code>{info.connector_url}</code>
  </div>
  <div class="row">
    <button onclick={copyConnector}>{copied ? 'Copied' : 'Copy URL'}</button>
    <button class="secondary" onclick={rotate}>Make a new URL</button>
  </div>
  <p class="muted">Anyone with this URL can generate images on your GPU account. Treat it like a password.</p>
  {#if !info.generator}<p class="muted">It works once step 1 is done.</p>{/if}
</section>
